"""PDF text extraction. Adapted from fs-v2/agentic_search/ingestion.py.

Text-native PDFs (generated by billing software) yield clean text via
pypdfium2. Scanned/image PDFs yield little or no text — callers should
treat low text yield as a signal to route through the vision LLM instead.
"""

from __future__ import annotations

from dataclasses import dataclass
from io import BytesIO

import pypdfium2
import tiktoken


_enc = tiktoken.get_encoding("o200k_base")


@dataclass
class PageText:
    page_number: int
    text: str
    token_count: int


def count_tokens(text: str) -> int:
    return len(_enc.encode(text))


def extract_pages_from_pdf_bytes(data: bytes) -> list[PageText]:
    """Extract text from every page of a PDF.

    Pages with no text (scanned images) are included with empty `text` so
    page numbering stays intact for the caller.
    """
    pdf = pypdfium2.PdfDocument(BytesIO(data))
    pages: list[PageText] = []
    try:
        for i in range(len(pdf)):
            text = pdf[i].get_textpage().get_text_range().strip()
            pages.append(
                PageText(
                    page_number=i + 1,
                    text=text,
                    token_count=count_tokens(text) if text else 0,
                )
            )
    finally:
        pdf.close()
    return pages


def is_text_native_pdf(pages: list[PageText], min_chars: int = 50) -> bool:
    """True if the PDF's pages carry enough extracted text that we can skip
    the vision LLM for classification/extraction.

    Default threshold: at least one page with 50+ characters.
    """
    return any(len(p.text) >= min_chars for p in pages)


def concat_pages(pages: list[PageText], max_chars: int = 20000) -> str:
    """Join page texts with page markers, capped at `max_chars`."""
    out: list[str] = []
    total = 0
    for p in pages:
        block = f"--- Page {p.page_number} ---\n{p.text}"
        if total + len(block) > max_chars:
            break
        out.append(block)
        total += len(block)
    return "\n\n".join(out)
